services:
  - type: web
    name: eapcet-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python scripts/csv_to_db.py --rebuild"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
